FROM ubuntu:18.04

# install tools
RUN apt update
RUN apt install -y git
RUN apt install -y vim
RUN apt install -y npm
# RUN npm install react-chartjs-2
# RUN npm install react-sigma


# download code
RUN mkdir example
WORKDIR /example
RUN git clone https://github.com/amkorousagi/trendup_back.git

# environment
EXPOSE 6002

# when run builded image
# CMD

# when run
# docker run --rm -it -p <external port>:<container port> --name <container name> <docker imamge id or name> <command>
